[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true
# Allow forge script to write deployment artifacts to the deployments folder
# See: https://book.getfoundry.sh/reference/config/fs-permissions
fs_permissions = [
	{ access = "read", path = "./" },
	{ access = "write", path = "./deployments" }
]

# Base Sepolia Configuration
[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", chain = 84532, url = "https://api-sepolia.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
