/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { TribeCopyVault } from "./TribeCopyVault";
export type { TribeVaultFactory } from "./TribeVaultFactory";
export * as factories from "./factories";
export { IERC20__factory } from "./factories/IERC20__factory";
export { TribeCopyVault__factory } from "./factories/TribeCopyVault__factory";
export { TribeVaultFactory__factory } from "./factories/TribeVaultFactory__factory";
